# Generated by Django 2.2.1 on 2019-06-12 07:45

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.CharField(default=events.models._generate_event_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Event ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
