# Generated by Django 2.2.1 on 2019-06-14 03:25

import activities.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20190612_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.CharField(default=activities.models._generate_activity_item_key, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Activity ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Poll'), (1, 'Note')], editable=False, verbose_name='Activity Type')),
                ('pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
