# Generated by Django 2.2.1 on 2019-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityitem',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'poll'), (1, 'note')], editable=False, verbose_name='Activity Type'),
        ),
    ]
