# Generated by Django 2.2.1 on 2019-05-29 06:31

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.CharField(default=group.models._generate_group_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Group ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
