# Generated by Django 2.2.1 on 2019-06-14 03:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('activityitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.ActivityItem')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('activities.activityitem',),
        ),
    ]
