# Generated by Django 2.2.1 on 2019-06-14 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('activityitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.ActivityItem')),
                ('question', models.CharField(max_length=100, verbose_name='Question')),
                ('multiple', models.BooleanField(default=False, verbose_name='Allow Multiple Votes')),
                ('change', models.BooleanField(default=True, verbose_name='Allow Changing Vote')),
                ('hide_results', models.BooleanField(default=True, verbose_name='Hide Results Until Voted')),
            ],
            options={
                'abstract': False,
            },
            bases=('activities.activityitem',),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.CharField(default=polls.models._generate_poll_option_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Poll Option ID')),
                ('text', models.CharField(max_length=250, verbose_name='Option Text')),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='Order')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.Poll')),
            ],
            options={
                'ordering': ('order', 'date_created'),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.CharField(default=polls.models._generate_vote_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Vote ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'option'), name='unique_vote'),
        ),
    ]
