# Generated by Django 2.2.1 on 2019-06-12 07:45

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.CharField(default=polls.models._generate_poll_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Poll ID')),
                ('question', models.CharField(max_length=100, verbose_name='Question')),
                ('multiple', models.BooleanField(default=False, verbose_name='Allow Multiple Votes')),
                ('change', models.BooleanField(default=True, verbose_name='Allow Changing Vote')),
                ('hide_results', models.BooleanField(default=True, verbose_name='Hide Results Until Voted')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.CharField(default=polls.models._generate_poll_option_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Poll Option ID')),
                ('text', models.CharField(max_length=250, verbose_name='Option Text')),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='Order')),
            ],
            options={
                'ordering': ('order', 'date_created'),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('id', models.CharField(default=polls.models._generate_vote_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Vote ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollOption')),
            ],
        ),
    ]
