# Generated by Django 2.2.1 on 2019-06-03 15:52

from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.CharField(default=groups.models._generate_group_key, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='Group ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('thumb', models.URLField(blank=True, null=True, verbose_name='Thumbnail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.CharField(default=groups.models._generate_invite_key, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Invite ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(default=groups.models._generate_membership_key, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Membership ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
    ]
